language: python
python:
  - 3.6
install:
  - "pip install scipy"
  - "pip install numpy"
  - "pip install matplotlib"
  - "git clone https://github.com/ghliu/pyReedsShepp"
  - "cd ./pyReedsShepp"
  - "sudo python setup.py install"
script:
  - python --version
  - python -m unittest discover tests
